---
- name: Download WordPress
  get_url: url=http://wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/opt/wordpress-{{ wp_version }}.tar.gz
           sha256sum="{{ wp_sha256sum }}"

- name: Extract archive
  command: chdir=/opt/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/opt/wordpress/

- name: Create WordPress database
  mysql_db: name={{ wp_db_name }} state=present
  become: true

- name: Create WordPress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present
  become: true

- name: Copy WordPress config file
  template: src=wp-config.php dest=/opt/wordpress/

  become: true

- name: Change ownership of WordPress installation
  file: path=/opt/wordpress/ owner=www-data group=www-data state=directory recurse=yes

- name: Restart nginx
  service: name=nginx state=restarted
